# **Primera I.A.**

Enseñemos a Sumar

Autor: M.B.A. Ing. Dipl.  Luis Vidal V. (lvidal@uach.cl)

Fecha: 27 de agosto de 2021



# Importar librerias

In [1]:
import pandas as pd
import numpy as np

# Carga de datos

In [2]:
# Se emple la función wget que permita bajar al espacio de trabajo los datos para análisis
!wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/luisvidalvidal/cursoIA/main/suma.csv

# Ustilizando pandas, se carga archivo en memoria como dataframe
df = pd.read_csv("suma.csv")
df.head(10)

--2021-10-20 01:14:57--  https://raw.githubusercontent.com/luisvidalvidal/cursoIA/main/suma.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20530 (20K) [text/plain]
Saving to: ‘suma.csv’

suma.csv            100%[===================>]  20.05K  --.-KB/s    in 0s      

2021-10-20 01:14:58 (84.7 MB/s) - ‘suma.csv’ saved [20530/20530]



Y    X1    X2
0     10     5     5
1  16057  6528  9529
2   6940  2988  3952
3   1869   266  1603
4   1037   594   443
5  13837  8881  4956
6   9360  9059   301
7  11445  8003  3442
8  10067  3593  6474
9  14906  7550  7356

In [3]:
df = pd.read_csv('suma.csv')

In [4]:
#Muestra columnas
print(df.columns)

Index(['Y', 'X1', 'X2'], dtype='object')


In [5]:
#Creamos un dataset desde el archivo que se descargo.
dataset = df.values

In [6]:
print(dataset)

[[   10     5     5]
 [16057  6528  9529]
 [ 6940  2988  3952]
 ...
 [11842  9240  2602]
 [ 4874  4758   116]
 [ 4950  4472   478]]


In [7]:
#Separamos los datos Y variable objetivo, X variables x1 y x2
Y=dataset[:,0]
X=dataset[:,1:3]

In [8]:
#Usar este código para dejar los tipos de datos como float, sugerido.
X=np.asarray(X).astype(np.float32)
Y=np.asarray(Y).astype(np.float32)

In [9]:
print(X)
print(Y)

[[5.000e+00 5.000e+00]
 [6.528e+03 9.529e+03]
 [2.988e+03 3.952e+03]
 ...
 [9.240e+03 2.602e+03]
 [4.758e+03 1.160e+02]
 [4.472e+03 4.780e+02]]
[1.0000e+01 1.6057e+04 6.9400e+03 ... 1.1842e+04 4.8740e+03 4.9500e+03]


# Creación del Cerebro de nuestra la I.A.

In [10]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [11]:
#Cerebro
def build_model():
  model = keras.Sequential([
    layers.Dense(16, activation='relu', input_shape=[2]),   #input_shape  se ingresa cantida de Xi
    layers.Dense(32, activation='relu'),
    layers.Dense(18, activation='relu'),
    layers.Dense(1)
  ])
  optimizer = tf.keras.optimizers.RMSprop(learning_rate=0.0001)
  model.compile(loss='mse',
                optimizer=optimizer,
                metrics=['mae', 'mse'])
  return model

In [12]:
#Se crea el modelo Cerebro (modelo de redes neuronales)
model = build_model()

# Entrenamiento de la Red Neuronal

In [13]:
!pip install git+https://github.com/tensorflow/docs

  Cloning https://github.com/tensorflow/docs to /tmp/pip-req-build-t50g68rq
  Running command git clone -q https://github.com/tensorflow/docs /tmp/pip-req-build-t50g68rq
  Created wheel for tensorflow-docs: filename=tensorflow_docs-0.0.0.dev0-py3-none-any.whl size=157743 sha256=db74e920ff0a4a6136b28b2e70fa9c3bd9dc7d26374a34114e74118b519dcdd4
  Stored in directory: /tmp/pip-ephem-wheel-cache-_s4933n6/wheels/cc/c4/d8/5341e93b6376c5c929c49469fce21155eb69cef1a4da4ce32c
Successfully built tensorflow-docs


In [14]:
import tensorflow_docs as tfdocs
import tensorflow_docs.modeling

In [15]:
EPOCHS = 1000

In [16]:
history = model.fit(
    X,Y,
    epochs=EPOCHS, verbose=0,
    callbacks=[tfdocs.modeling.EpochDots()])


Epoch: 0, loss:130600912.0000,  mae:10535.1211,  mse:130600912.0000,  
....................................................................................................
Epoch: 100, loss:169.4391,  mae:10.8673,  mse:169.4391,  
....................................................................................................
Epoch: 200, loss:148.1082,  mae:8.4367,  mse:148.1082,  
....................................................................................................
Epoch: 300, loss:184.4962,  mae:11.3455,  mse:184.4962,  
....................................................................................................
Epoch: 400, loss:159.3746,  mae:9.1270,  mse:159.3746,  
....................................................................................................
Epoch: 500, loss:198.3997,  mae:10.8399,  mse:198.3997,  
....................................................................................................
Epoch: 600, loss:167.3331,  mae:11

# Prueba de la I.A. creada, que tenía como objeto enseñar a sumar a nuestra I.A.

In [17]:
print("Aprendiendo a sumar")

a=float(input("Ingrese primer valor: "))
b=float(input("Ingrese segundo valor: "))

y=model.predict(np.array([[a,b]]))

#suma=a+b
#error_absoluto=abs(suma-y)

print(" ")
print("El resultado es: %s apróximadamente " % y[0] [0])


#print(" ")
#print("El error absoluto es de %s:" % error_absoluto[0][0])


Aprendiendo a sumar
Ingrese primer valor: 4
Ingrese segundo valor: 1
 
El resultado es: 5.2202115 apróximadamente 
